import os
import time
import base64
import numpy as np
import scipy.signal as signal
from scipy.signal import butter, sosfilt
import soundfile as sf
from pathlib import Path
from google import genai
from google.genai import types

BASE_DIR = Path(__file__).resolve().parent
AUDIO_DIR = BASE_DIR / "audio" / "voice_samples"
AUDIO_DIR.mkdir(parents=True, exist_ok=True)
CACHE_DIR = AUDIO_DIR / "weekend_recap_cache"
CACHE_DIR.mkdir(parents=True, exist_ok=True)

ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.strip().startswith("#"):
            k, v = line.strip().split("=", 1)
            os.environ[k] = v

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY", ""))

# Full Weekend AI & Tech Recap Dialogue Script (12 Turns, ~3 Minutes)
WEEKEND_FULL_SCRIPT = [
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[upbeat] Happy Saturday morning, everyone! Welcome to the Future Human Daily Weekend Recap. Alex and Elena are off taking a well-deserved break today and will be back bright and early Monday morning—so I am Veda with Rami, and we are kicking back with your Saturday morning coffee."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[chuckles] [warmly] That is right! No heavy quantum physics equations or skull-drilling neurotech today, folks. Just pure weekend vibes, warm coffee, and the funniest, wildest tech stories that broke this week."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[playfully] Speaking of wild, Rami... did you catch that viral video of the brand-new humanoid household robot trying to fold laundry?"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[laughs] Oh, I replayed that video three times! It took five full minutes of deep neural processing just to fold one basic t-shirt, and then it accidentally launched the matching sock straight across the living room! [chuckles] Honestly, that is still better than my college roommate used to do."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[giggles] Exactly! The robot stood there looking so proud of itself afterwards too! But hey, story number two... an AI music model just composed an entire nineteen-eighties synth-wave album from scratch, and it is actually trending on top electronic charts."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[amazed] Right? I put on track three during my morning jog today, Veda. I am telling you, you literally cannot tell if that track was generated by a multi-billion parameter transformer model or a guy wearing neon leg warmers in nineteen-eighty-four."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[thoughtfully] It really raises some fun questions about retro music nostalgia, doesn't it? If an algorithm can capture the exact analog warmth of vintage synthesizer reels, what makes eighties synth music feel human to us?"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[chuckles] Well, as long as the AI doesn't start bringing back mullet haircuts, Veda, I think we are safe for now!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[laughs] Fair point! And finally, story number three... a coffee shop in Tokyo just started testing autonomous drone delivery for hot espresso directly to high-rise apartment balconies."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[excitedly] Now that is a technology I can get behind! Imagine stepping out onto your sixth-floor balcony in your bath robe, and a tiny quadcopter hands you a fresh double shot of espresso without a single drop spilled."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[playfully] Unless there is a gust of wind, Rami! Then you get a free espresso face wash! [giggles]"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[laughs] [warmly] Touché! Well, grab another cup of coffee, relax, and enjoy your weekend, folks. Alex and Elena will be back in the studio bright and early Monday morning—until then, keep having fun with the future!"
    }
]

def clean_turn(x, sr=24000, gap_ms=60, max_artifact_ms=250, flat_thresh=0.3):
    """Spectral Flatness Measure & Active Energy Run Grouping algorithm."""
    x = np.asarray(x)
    if x.dtype == np.int16:
        x = x.astype(np.float32) / 32768.0
    x = x.astype(np.float32) - x.mean()                 # remove DC

    hp = sosfilt(butter(4, 80, 'hp', fs=sr, output='sos'), x)
    fl = int(0.010 * sr)                                # 10 ms frames
    n = len(hp) // fl
    if n == 0: return x
    fr = hp[:n * fl].reshape(n, fl)

    db = 20 * np.log10(np.sqrt((fr ** 2).mean(1)) + 1e-9)
    active = db > (np.percentile(db, 95) - 35)

    spec = np.abs(np.fft.rfft(fr * np.hanning(fl), axis=1)) + 1e-9
    flat = np.exp(np.log(spec).mean(1)) / spec.mean(1)  # spectral flatness

    runs, s, last = [], None, None
    gap = gap_ms // 10
    for i, a in enumerate(active):
        if a:
            if s is None: s = i
            last = i
        elif s is not None and i - last > gap:
            runs.append((s, last + 1)); s = None
    if s is not None: runs.append((s, last + 1))
    if not runs: return x

    # drop trailing short, noise-like runs (the "kshhh")
    while len(runs) > 1:
        a, b = runs[-1]
        if (b - a) * 10 < max_artifact_ms and flat[a:b].mean() > flat_thresh:
            runs.pop()
        else:
            break

    start = max(0, runs[0][0] * fl - int(0.03 * sr))
    end = min(len(x), runs[-1][1] * fl + int(0.06 * sr))  # keep natural decay
    y = x[start:end].copy()

    fi, fo = int(0.008 * sr), int(0.05 * sr)              # short fade in, longer fade out
    if len(y) > fi + fo:
        y[:fi] *= np.linspace(0, 1, fi)
        y[-fo:] *= np.cos(np.linspace(0, np.pi / 2, fo)) ** 2
    return y

def apply_studio_warmth_eq(audio_samples, sample_rate=24000, low_boost_db=4.0):
    """Broadcast Studio Proximity Warmth EQ Pass (+4.0 dB @ 150Hz)."""
    f0 = 150.0
    Q = 0.9
    gain_db = low_boost_db
    A = 10 ** (gain_db / 40.0)
    w0 = 2 * np.pi * f0 / sample_rate
    alpha = np.sin(w0) / (2 * Q)
    
    b0 = 1 + alpha * A
    b1 = -2 * np.cos(w0)
    b2 = 1 - alpha * A
    a0 = 1 + alpha / A
    a1 = -2 * np.cos(w0)
    a2 = 1 - alpha / A

    b_eq = np.array([b0, b1, b2]) / a0
    a_eq = np.array([a0, a1, a2]) / a0

    return signal.filtfilt(b_eq, a_eq, audio_samples)

def generate_full_weekend_recap():
    print("==========================================================", flush=True)
    print("Generating Full Weekend AI & Tech Recap Sample (Veda & Rami)", flush=True)
    print("==========================================================", flush=True)

    sample_rate = 24000
    cleaned_dialogue = []
    pause_200ms = np.zeros(int(sample_rate * 0.20), dtype=np.float32)

    for idx, turn in enumerate(WEEKEND_FULL_SCRIPT):
        speaker = turn["speaker"]
        voice = turn["voice"]
        text = turn["text"]
        cache_file = CACHE_DIR / f"turn_recap_{idx+1:02d}_{speaker}.npy"

        raw_samples = None
        if cache_file.exists():
            print(f" -> Turn {idx+1}/{len(WEEKEND_FULL_SCRIPT)} [{speaker}] loaded from CACHE", flush=True)
            raw_samples = np.load(str(cache_file))
        else:
            success = False
            for attempt in range(8):
                try:
                    resp = client.models.generate_content(
                        model='gemini-3.8-flash-tts',
                        contents=text,
                        config=types.GenerateContentConfig(
                            response_modalities=["AUDIO"],
                            speech_config=types.SpeechConfig(
                                voice_config=types.VoiceConfig(
                                    prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name=voice)
                                )
                            )
                        )
                    )
                    part = resp.candidates[0].content.parts[0]
                    if part.inline_data:
                        data = part.inline_data.data
                        if isinstance(data, str): data = base64.b64decode(data)
                        raw_samples = np.frombuffer(data, dtype=np.int16).astype(np.float32) / 32768.0
                        np.save(str(cache_file), raw_samples)
                        print(f" -> Turn {idx+1}/{len(WEEKEND_FULL_SCRIPT)} [{speaker}] synthesized via gemini-3.8-flash-tts!", flush=True)
                        success = True
                        break
                except Exception as e:
                    print(f"    Attempt {attempt+1}: Quota delay ({e}), waiting 12s...", flush=True)
                    time.sleep(12)
                if success: break

        if raw_samples is not None:
            # 1. Clean turn using Spectral Flatness algorithm
            t_clean = clean_turn(raw_samples, sample_rate)
            # 2. Apply Studio Proximity Warmth EQ (+4.0 dB @ 150Hz)
            t_warm = apply_studio_warmth_eq(t_clean, sample_rate, low_boost_db=4.0)

            cleaned_dialogue.append(t_warm)
            cleaned_dialogue.append(pause_200ms)
            time.sleep(3)

    if not cleaned_dialogue:
        print("[Error] No turns available to master.", flush=True)
        return

    full_dialogue = np.concatenate(cleaned_dialogue)

    # Add continuous warm studio room tone (-52 dBFS) under the WHOLE episode
    np.random.seed(42)
    noise = np.random.randn(len(full_dialogue)).astype(np.float32)
    b_lp, a_lp = signal.butter(2, 350 / (sample_rate / 2), btype='low')
    room_tone = signal.filtfilt(b_lp, a_lp, noise)
    room_tone /= (np.max(np.abs(room_tone)) + 1e-6)
    room_tone *= 10 ** (-52.0 / 20.0) # -52 dBFS continuous room tone

    mastered = full_dialogue + room_tone
    max_p = np.max(np.abs(mastered))
    if max_p > 0: mastered *= (0.891 / max_p)

    out_mp3 = AUDIO_DIR / "sample_31_full_weekend_recap_veda_rami.mp3"
    out_wav = AUDIO_DIR / "sample_31_full_weekend_recap_veda_rami.wav"

    sf.write(str(out_wav), mastered, sample_rate)
    sf.write(str(out_mp3), mastered, sample_rate)

    duration = len(mastered) / sample_rate
    print("==========================================================", flush=True)
    print(f"[COMPLETE] Saved Full Weekend Recap Sample 31: {out_mp3}", flush=True)
    print(f"Duration: {duration/60:.2f} minutes ({len(mastered)/sample_rate:.1f}s across {len(WEEKEND_FULL_SCRIPT)} turns)", flush=True)
    print("==========================================================", flush=True)

if __name__ == "__main__":
    generate_full_weekend_recap()
