import os
import sys
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

SATURDAY_SCRIPT_30_TURNS = [
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[upbeat] Happy weekend, everyone! Welcome to the Future Human Daily Weekend Recap. Alex and Elena are off taking a well-deserved break today and will be back bright and early Monday morning—so I am Veda with Rami, and we are kicking back with your Saturday morning coffee."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[chuckles] [warmly] That is right! No heavy quantum physics equations or complex tensor calculus today, folks. Just pure weekend vibes and the funniest, wildest tech stories that broke across the world this week."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[playfully] Speaking of wild, Rami... did you catch that viral video of the new humanoid robot trying to fold laundry in a living room?"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[warmly] Oh, I replayed it three times! It took five full minutes to fold one t-shirt, carefully lining up the sleeves, and then suddenly threw the matching sock across the living room! [chuckles] Honestly, that is still better than my college roommate used to do."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[giggles] Exactly! But jokes aside, what makes that robot so interesting is the tactile force-feedback sensors in its fingers. Most older robots were rigid, so if a shirt bunched up, the robot would rip the fabric or lose grip."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] Right, this new model uses micro-capacitive arrays along each fingertip. It can literally feel the friction and softness of silk versus denim in real time."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[cheerful] So even though it flung a sock across the room, it did not tear the cotton! The engineering team said the neural network controlling its wrist motor had a tiny micro-second prediction latency spike, which caused the sudden flick."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[playfully] [chuckles] A latency spike! That is going to be my new excuse when I spill coffee on my shirt. 'Sorry everyone, my neural motor control suffered a latency spike!'"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[laughs] I am definitely using that one on Monday! But seriously, household robotics are moving out of pristine research labs and into chaotic real-world apartments. And that brings us right to how these robots handle unpredictable home environments."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[warmly] Well, in a lab, everything is flat, brightly lit, and predictable. Put that same robot on a shag rug with a golden retriever running around, and suddenly spatial mapping becomes a real adventure."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[thoughtfully] Exactly. The robotics team had to train vision-language models on thousands of hours of chaotic home videos just so the robot could distinguish between a dropped towel and a sleeping cat!"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[chuckles] That is a pretty crucial distinction if you do not want your cat launched across the room like that sock!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[playfully] Very crucial! Alright, take a sip of your coffee, because let us move to our next story, which was about something completely unexpected in the music industry."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[excitedly] Ah, yes! An AI music system composed an entire nineteen-eighties synthwave album that is actually climbing the top charts!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] I listened to track three on my morning walk today. You literally cannot tell if it was produced by a human synth maestro in nineteen-eighty-four or generated by a neural audio model running on a GPU cluster."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] What got me was the drum sound. It perfectly captured that warm, analog LinnDrum reverb and those cheesy synth brass stabs. How did the model get that dynamic human groove so right?"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[cheerful] The researchers trained a multi-track diffusion transformer directly on raw uncompressed stem files from classic hardware synthesizers—like the Yamaha DX7 and Sequential Circuits Prophet-5."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[impressed] Wow, so instead of just stitching together audio loops, it models the actual voltage fluctuations and non-linear distortion of analog circuits?"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[excitedly] Precisely! Down to the slight pitch drift when the virtual synth components heat up over time. It gives the music that human imperfection that pristine digital synths often miss."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[chuckles] [playfully] So virtual synths now get virtual fever and warming up periods! That is fascinating."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] It really is. But of course, it raised huge debates online about music licensing and whether an AI album should be eligible for music awards."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] Right. Musicians are asking: if the model learned its synth pads from decades of human artists, how do we credit and compensate those original creators?"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[cheerful] That conversation is going to be central all year. Okay, let us move to our final story for today, which takes us up into the sky!"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[excitedly] Autonomous coffee delivery drones in suburban neighborhoods! This one feels straight out of a sci-fi movie."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] Imagine ordering a hot iced latte on your phone, and four minutes later, a silent hexacopter hovers thirty feet above your front lawn and lowers your coffee on a gentle micro-tether."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[playfully] [chuckles] Silent hexacopter? Because the older delivery drones sounded like a swarm of angry mechanical bees hovering over your garden!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[giggles] They really did! But these new drones use toroidal propeller blades. The closed loop tip design eliminates the high-frequency acoustic vortex, dropping noise levels by over twelve decibels."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] Twelve decibels is a massive reduction—that makes it sound more like a soft rustling breeze than a leaf blower."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] And the tether winch mechanism has active gyroscopic stabilization. Even in twenty knot wind gusts, your coffee cup stays completely upright without spilling a single drop."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[cheerful] Now that is true engineering progress! Delivering caffeine safely through windstorms."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[upbeat] Absolutely! What a fun lineup of stories today. Enjoy the rest of your Saturday, take it easy, and remember—Alex and Elena will be back bright and early Monday morning for your daily deep dive. Until then, stay curious!"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[warmly] Have a wonderful weekend, everyone! See you Monday!"
    }
]

SUNDAY_SCRIPT_30_TURNS = [
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[upbeat] Happy Sunday, everyone! Welcome to the Future Human Daily Sunday Recap. Alex and Elena will be back tomorrow morning for Monday's main show—so I am Veda with Rami, bringing you the big AI catchup and weekly tech deep dives."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[warmly] Happy Sunday! Today we are looking back at the major breakthroughs, model releases, and security stories that defined the week. Grab your coffee and let us dive in!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[excitedly] Let us start with the biggest release of the week: the announcement of Claude Opus 5.5 and its unprecedented long-context reasoning capabilities."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] Opus 5.5 has been the main topic in developer communities all week. The benchmark jumps in complex multi-step coding and mathematical proofs are remarkable."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[cheerful] What really caught my attention was its ability to hold an entire million-token repository in active attention without losing precision or hallucinating imports."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[warmly] Right. In earlier generations, as context windows expanded, models suffered from what researchers call the 'needle in a haystack' drop-off in the middle of long documents."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[excitedly] Exactly! But Opus 5.5 uses a novel hierarchical attention routing architecture that keeps middle-context retrieval accuracy at nearly ninety-nine percent."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[playfully] That means developers can feed an entire legacy codebase into the model, ask it to refactor a hidden concurrency bug, and get back working code in seconds."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[chuckles] No more spending three days hunting for missing semicolons or race conditions!"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] But beyond coding, the multimodal capabilities have improved drastically. It can analyze intricate circuit schematics, architectural blueprints, and medical imaging simultaneously."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] That cross-domain synthesis is where frontier models are becoming genuine cognitive partners rather than simple text generators."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[cheerful] Well said, Veda. Now, let us move to our next major story from this past week, which hit the cybersecurity world."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[serious] Yes, a team of ethical AI security researchers demonstrated the first fully autonomous AI threat hunting agent operating in live enterprise networks."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] Traditional intrusion detection systems rely on static signatures—looking for known malware hashes. But modern zero-day attacks use polymorphic code that changes constantly."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] Exactly. This new AI agent does not look for signatures. Instead, it monitors behavioral anomalies across network traffic, memory allocations, and system kernel calls."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[excitedly] In benchmark tests, when a simulated zero-day exploit attempted to escalate privileges, the AI agent detected the anomaly within forty milliseconds and automatically generated a targeted micro-patch!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[impressed] Forty milliseconds! That is faster than a human security analyst can even open a terminal window."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[playfully] [chuckles] Human analysts would still be waiting for their morning coffee to brew while the AI agent resolved three cyber intrusions!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[laughs] Exactly! But cybersecurity experts emphasized that keeping human security leads in the loop for final authorization is still critical to prevent accidental network lockouts."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] Right. AI handles the ultra-fast detection and draft patch generation, while human experts oversee security governance."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[cheerful] Alright, let us move to our final Sunday story, which comes from the frontier of clean energy and quantum material science."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[excitedly] Researchers used quantum computer simulations to discover a new class of solid-state battery electrolytes that could charge electric vehicles in under five minutes!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] Five minutes! The key obstacle with solid-state batteries has always been lithium dendrite formation—tiny crystal whiskers that short-circuit battery cells during fast charging."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[thoughtfully] By modeling atomic ionic transport at the quantum level, the researchers designed a self-healing crystalline lattice that prevents dendrite growth entirely."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[cheerful] This means solid-state batteries can achieve twice the energy density of current lithium-ion cells while being completely non-flammable."
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[playfully] Charging your electric car in five minutes with zero risk of battery fires? That completely eliminates range anxiety."
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[warmly] It really does. What an exciting week of scientific and technological progress!"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[cheerful] It has been a fantastic Sunday recap. Remember, Alex and Elena will be back bright and early tomorrow morning for Monday's main show!"
    },
    {
        "speaker": "Veda",
        "voice": "Veda",
        "text": "[upbeat] That is right! Have a relaxing Sunday evening, enjoy your weekend, and join Alex and Elena tomorrow morning. Until then, keep exploring!"
    },
    {
        "speaker": "Rami",
        "voice": "Rami",
        "text": "[warmly] Take care, everyone! See you tomorrow!"
    }
]

def get_weekend_script(is_sunday=False):
    return SUNDAY_SCRIPT_30_TURNS if is_sunday else SATURDAY_SCRIPT_30_TURNS

if __name__ == "__main__":
    is_sun = "--sunday" in sys.argv
    script = get_weekend_script(is_sunday=is_sun)
    day = "Sunday" if is_sun else "Saturday"
    word_count = sum(len(t["text"].split()) for t in script)
    print(f"Generated {day} Weekend Script: {len(script)} turns, {word_count} total words (~{word_count/300:.1f} mins spoken duration).")
