# =============================================================================
# THE UNWRITTEN CODE: MASTER SCRIPTS DATABASE
# Mandatory Guideline: 1,550 – 1,750 words (24–28 alternating turns) for weekdays
# Target Duration: 5:15 – 6:30 minutes
# Quality Gate: Word count assertion >= 1,500 words for every weekday episode
# =============================================================================

def get_script_for_day(day_idx):
    """
    Returns (episode_number, title, summary, script_turns) based on weekday.
    Strictly guaranteed 1,550 - 1,750 words (>= 1,500 words minimum) for every weekday episode.
    """
    # -------------------------------------------------------------------------
    # MONDAY = 0: Workplace & Slack Etiquette (1,644 words)
    # -------------------------------------------------------------------------
    if day_idx == 0:
        ep_num = 1
        title = "The Slack Thumbs-Up vs. The Reply-All Disaster"
        summary = "Maya & Julian launch The Unwritten Code by unpacking modern workplace messaging anxiety: why does a thumbs-up emoji on Slack feel passive-aggressive, the agony of the 'No-Hello' typing bubble, and who is still hitting reply-all to company emails?"
        turns = [
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Happy Monday, everyone! Welcome to the official premiere of The Unwritten Code! I am Maya Lin, and if you are listening to this on your morning commute, sitting at your desk with your second cup of coffee, or hiding in the office kitchen avoiding your inbox, you are in the exact right place. Today is Monday, October fifth, which means we are inaugurating this show by diving headfirst into the chaotic, passive-aggressive jungle known as modern workplace communication."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] And I am Julian Cross. Maya, I have to say, there is no better way to kick off Episode One than with the corporate danger zone. Every single one of us spends forty to fifty hours a week staring at glowing screens, deciphering micro-messages, decoding emoji nuances, and pretending we understand what our coworkers actually mean when they type three innocent words. Society spent thousands of years developing vocal tone, facial expressions, and body language, and then within ten years, corporate software compressed all human intimacy down into unformatted text bubbles on Slack and Teams."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] It really is an emotional battlefield! And the single biggest flashpoint in the modern office right now is one humble, yellow digital icon: the Slack thumbs-up emoji. Julian, let me set the scene for you. An employee spends three solid hours pouring their heart, soul, and intellect into a comprehensive, beautifully structured project update. They hit send, their pulse is racing, and two minutes later, their manager reacts with a single, naked, yellow thumbs-up emoji. Tell me: what is the psychological fallout of that moment?"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Absolute existential terror, Maya! My heart plunges straight through the floorboards. I immediately minimize the window, stare blankly out the window, and spend the next forty-five minutes frantically re-reading every single syllable of my update to figure out if I am about to get fired, demoted, or placed on a secret performance improvement plan! [sighs] The thumbs-up emoji is the most emotionally ambiguous gesture in human history. Does it mean Great job? Does it mean I acknowledge your existence? Or does it mean I am deeply disappointed in you, but I do not have the patience to type real words?"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] That is the genius and the horror of it! What we have here is the great generational divide of the corporate world. If you talk to anyone in senior leadership who grew up with flip phones and fax machines, a thumbs-up emoji is the pinnacle of workplace efficiency. To them, it simply means: Message received, thank you, keep moving. But to anyone under thirty-five, receiving a lone thumbs-up feels like someone looked you directly in the eyes in the hallway, said nothing, and slowly closed the elevator door in your face with a blank expression!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] [warmly] It has zero emotional warmth, Maya! It is cold, robotic, and transactional. It is the digital equivalent of texting someone the letter K with a period at the end! If you receive a text from a friend that says K with a period, you immediately assume the friendship is over and they are blocking your number. The thumbs-up carries that exact same chilling energy in a direct message. If you want to encourage your team, use the celebration party popper! Use the green checkmark! Use the little dancing penguin! Use literally anything in the emoji library except the cold, unfeeling thumb of doom!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] I could not agree more, Julian! But wait, because workplace messaging crimes do not stop at emojis. Let us talk about what I call the Hello Hostage Situation. You are sitting at your desk, deep in your zone, making actual progress on a spreadsheet. Suddenly, your notification dings: Dave from Marketing says: Hey Maya. And then... nothing. Silence. Just that little pencil icon bouncing: Dave is typing... Dave stopped typing... Dave is typing again. Julian, why do people do this?!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Oh, it is psychological torture! Why are you holding my attention hostage with a two-word greeting? Tell me what you want in the same breath! When someone sends just Hey Julian, they are demanding that I stop whatever I am doing, reply with Hey Dave, and wait for them to spend three agonizing minutes composing their actual question. There is a whole website dedicated to this called No Hello! Just type: Hey Julian, quick question about the budget numbers, do you have five minutes later today? Boom, done, professional, respectful of my sanity!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] Exactly! Respect the time and respect the nervous system! But now, Julian, we have to address the undisputed heavyweight champion of workplace felonies. The crime against humanity that unites every corporate department from sales to engineering in collective agony: The Reply-All Disaster."},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [chuckles] Oh, heaven help us! Straight to corporate federal prison! Maya, walk us through how this horror show always unfolds."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] It always starts completely innocently. Human Resources or the Facilities team sends an email announcement to two thousand people across four global offices: Reminder: The cafeteria will be serving pumpkin soup this Thursday. Simple, right? But then, within ninety seconds, someone named Kevin in Regional Logistics accidentally clicks Reply-All instead of Reply, and broadcasts to all two thousand people: Sounds delicious, thanks team! And that is when the nuclear chain reaction begins."},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] Because thirty seconds later, three different people who think they are the email police hit Reply-All to say: Please stop replying all to this thread! And then five minutes later, eight more people hit Reply-All screaming: Why am I on this list? Please unsubscribe me! And within half an hour, the company exchange server is smoking in the IT closet, forty thousand redundant emails have clogged everyone's inboxes, and productive work has ground to a complete halt across three time zones!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[giggles] It is a self-sustaining cyclone of office madness! I once worked at an agency where a reply-all chain got so completely out of control that someone started replying all with sourdough bread recipes, another person attached photos of their golden retriever, and leadership had to send an emergency IT kill-switch memo shutting down the entire email server for the afternoon!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] See, this is why modern society is crumbling at the edges, Maya! We have sophisticated artificial intelligence, quantum computing, and autonomous electric vehicles, but human beings still cannot resist the primal urge to hit Reply-All and inform four thousand strangers that they enjoy pumpkin soup!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] And speaking of virtual workplace drama, Julian, what about modern meeting culture? Specifically, the awkward Camera-On Standoff. You log into a nine AM video call with your camera politely turned off, wearing a comfy hoodie and holding your tea, and the meeting host chirps: Hey everyone, let us all turn our cameras on so we can see all your lovely smiling faces this morning!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[sighs] [chuckles] The sheer panic! Your fight-or-flight response kicks in immediately! You are frantically scrambling to throw a collared dress shirt over your pajama pants, wiping sleep out of your eyes, kicking laundry baskets out of the webcam frame, and desperately toggling the background blur filter hoping it disguises the fact that you are sitting on your unmade bed!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] And the funniest secret of all, Julian, is that nobody on a video call is actually looking at the person speaking anyway! Behavioral studies have shown that during an eight-person Zoom meeting, people spend roughly eighty-five percent of the time staring exclusively at their own tiny video preview box in the corner, making sure their hair looks acceptable and adjusting their chin angle!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] It is pure vanity under the guise of collaboration! And of course, there is always the grand finale of every video meeting: the person who delivers an impassioned, three-minute speech on quarterly revenue while completely muted, gesturing wildly with their hands, until six people simultaneously unmute to scream: Bob, you are on mute! Bob, we cannot hear you!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Every single day, Julian! Which is why we created The Unwritten Code. Because somebody has to bring law, order, and sanity to the modern human experience. So right here on Episode One, let us officially hand down The New Code for surviving modern workplace communication."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Here is The Code. Rule Number One: The Emoji Upgrade Law. If you manage people, ban the naked thumbs-up emoji on Slack forever. If you want to acknowledge good work, use the green checkmark, the party popper, or pair your thumbs-up with three actual words like: Looks great, thanks! Save a life; upgrade your emoji."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Rule Number Two: The No-Hello Mandate. Never send a standalone greeting. Always include your actual request or question in the very same message. Your coworkers will respect you, your projects will move faster, and nobody has to stare at the bouncing typing bubble in terror."},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Rule Number Three: The Reply-All Felony Fine. If you reply-all to a company-wide announcement sent to more than twenty people just to say thanks or ask to be unsubscribed, you are officially obligated to buy gourmet coffee and donuts for your entire department on Friday morning."},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] And Rule Number Four: The Three-Sentence Email Boundary. If an email thread requires more than three back-and-forth messages, stop typing paragraphs. Pick up the phone or walk over for a sixty-second conversation. Protect your inbox sanity!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] That is The Unwritten Code for this Monday morning! What an incredible way to kick off our very first episode. If you resonated with any of these workplace struggles, do not forget to hit the Follow button right now on Spotify and Apple Podcasts so you never miss tomorrow morning's drop!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Tomorrow on Tuesday, we are leaving the office behind and diving straight into modern dating economics: who pays on date three, the awkward wallet reach, and why the slow-fade text is worse than ghosting. Until tomorrow morning, stay sane out there, and remember: do not break the code!"}
        ]

    # -------------------------------------------------------------------------
    # TUESDAY = 1: Modern Dating Economics & Romance Realities (1,625 words)
    # -------------------------------------------------------------------------
    elif day_idx == 1:
        ep_num = 2
        title = "Who Pays on Date Three? (And The Ghosting Slow-Fade)"
        summary = "Maya & Julian unpack modern dating etiquette: who pays on date three, the subtle art of the polite wallet reach, and why the slow-fade text message is emotional cowardice compared to honest closure."
        turns = [
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Welcome back to The Unwritten Code, everyone! I am Maya Lin alongside Julian Cross, and today is Tuesday, October sixth. Yesterday we survived corporate Slack warfare, the terror of the naked thumbs-up emoji, and the catastrophic reply-all chain email. But today, we are stepping into an even more dangerous, emotionally volatile, high-stakes arena: modern dating economics and the bizarre rituals of romance in the smartphone era."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] [chuckles] Oh boy, Maya. If you thought workplace passive-aggression was intense, wait until you sit across a candlelit Italian restaurant table from someone you have known for exactly three weeks, and the waiter places a tiny leather check booklet squarely in the geographic center of the table. Today's dilemma was submitted by a listener named Ryan from Chicago, who asks: On Date Three, who is actually responsible for picking up the bill?"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] It is the ultimate modern standoff! Think about the progression of dating economics across the first month. Date One is simple: traditional etiquette says whoever asked for the date usually offers, or you grab casual ten-dollar drinks and split the tab without overthinking it. Date Two, the other person often steps up and says: I've got this round, since you got dinner last time. But Date Three is the danger zone where all the unwritten scripts completely dissolve into awkward, sweating static!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] Exactly! Because Date Three is the psychological threshold. Date Three is the exact moment where you are no longer two polite strangers on a brief trial run, but you are also not an established couple with shared financial norms. If one person pays all three times, they start feeling like an unpaid patron of the arts or a sponsor for someone's weekend lifestyle! But if someone pulls out their smartphone calculator app and calculates seventy-five cents for truffle fries on Date Three, all romantic chemistry instantly evaporates into thin air!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] And let us talk about the performative choreography of The Wallet Reach! Julian, you know exactly what I am talking about because every single human being has either witnessed or executed this maneuver. The check lands on the mahogany table. Person A reaches for it. Person B does the slow-motion, half-hearted pat on their back pocket or reaches into their purse at two miles per hour, muttering: Oh, let me get this, are you sure? While their eyes are screaming: Please say no, please put your credit card down!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] It is an Oscar-worthy performance! Anthropologists literally call this performative generosity. If you pull out your credit card, you have to be willing to actually pay for the meal! You cannot deploy the decoy card as a theatrical prop and then look visibly panicked when the other person says: Thanks, that is so kind of you! If you offer the card, you must be spiritually and financially prepared to swipe it!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] But here is the deeper psychological question, Julian: why is talking about money on early dates still so profoundly taboo in twenty-twenty-six? We live in an era where people will openly share their deepest childhood traumas, their therapy breakthroughs, and their complex astrological birth charts on date one over tapas, but asking: Hey, how do you prefer handling dinner bills? feels like dropping an anvil on the romantic atmosphere!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Because money is tied directly to status, vulnerability, power dynamics, and unspoken expectations. In the old days, there was a rigid, outdated gender script where men paid automatically. Now we have equality, which is wonderful and overdue, but society never wrote the replacement rulebook! So people are navigating a high-stakes guessing game while trying to look effortlessly charming over artisanal sourdough and pasta."},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] And speaking of modern dating horrors, Julian, what about the communication rituals? Specifically, the cowardly phenomenon known as The Slow-Fade. We all know what ghosting is—disappearing into thin air like a magician with zero explanation after three weeks of texting. But the slow-fade is ten times more insidious and painful!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [chuckles] The slow-fade is psychological torture disguised as politeness! It is the coward's exit strategy! Maya, walk our listeners through the painful, day-by-day anatomy of how a slow-fade unfolds."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Week One: You are having great conversations, texting witty memes throughout the day, replying within twenty minutes. Week Two: Suddenly their replies take four to five hours, and the texts shrink to one sentence. Week Three: You text: Hey, want to grab dinner Thursday? And twenty-four hours later they reply: Ah, work is so crazy right now! Let's definitely reconnect soon though! With an exclamation mark! And then... radio silence for six full days. Julian, why can people not just be mature adults?!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[sighs] [warmly] Because people are terrified of temporary discomfort! Modern dating apps have trained people to treat human beings like browser tabs you can just leave open in the background until they eventually crash or get forgotten. The person doing the slow-fade tells themselves: I am being nice! I am sparing their feelings! No, you are not! You are holding someone in emotional limbo because you do not have the ten seconds of courage required to type a kind, honest, definitive sentence!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] Exactly! Just give me the clean execution! A clean rejection takes thirty seconds to digest, you have a slight sigh, you appreciate the honesty, and you move on with your week. The slow-fade drags out an imaginary scenario for three weeks while you check your phone wondering if they were in a minor bicycle accident, lost in a cave, or if they just do not like you!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] And what about the opposite crime, Maya? The Over-Communicator. The person who, after one decent two-hour coffee date where you discussed your favorite books, sends a four-hundred-word debrief paragraph at eleven PM recounting their emotional reactions to your conversation, followed by a voice memo at seven AM wishing you a magical Tuesday!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] [giggles] That is not a date, Julian, that is a podcast subscription! You have entered an aggressive parasocial contract with someone whose last name you do not even know yet! Sending unsolicited audio memos over ninety seconds before date three should require a signed waiver from both parties and a background check!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] [warmly] Exactly! Text cadence is an unwritten dance of reciprocity. You mirror the rhythm and length of the other person. If someone sends two sentences, you do not reply with an epic Russian novel! Keep the energy balanced, keep the intrigue alive, and save the life story for when you actually know where they grew up and their middle name."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] And Julian, what about read receipts? The little blue checkmarks or the words Read at 10:42 PM. Having read receipts turned on when you are dating someone new is like installing two-way surveillance cameras in your personal emotional life. If you read a message and don't respond for six hours, the other person isn't thinking you are busy at work; they are spiraling into an existential panic wondering which word in their last sentence caused offense!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] Turn them off immediately! Turn off read receipts, turn off last seen timestamps, and reclaim your digital peace of mind! Dating in twenty-twenty-six requires plausible deniability. You need to be able to read a message while walking across a crosswalk, pocket your phone, and reply when you actually have the emotional bandwidth to form a complete, witty sentence without looking like a monster."},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Which brings us to the heart of the matter. We cannot leave modern romance in this state of chaotic ambiguity and anxiety. So right here on Tuesday morning, let us officially draft The New Dating Code for all our listeners."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Here is The Code. Rule Number One: The Date Three Split or Take-Turns Law. By Date Three, the financial dynamic must normalize into an equal partnership. Either split the bill straight down the middle without hesitation, or the person who did not pay on Date Two covers Date Three. Zero shame, zero guesswork. Treat each other like equals."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Rule Number Two: The Sincere Wallet Rule. If you reach for your card, you must genuinely intend to pay the bill. If the other person takes you up on the offer, smile, hand over your card graciously, and do not make a passive-aggressive face at the waiter or sigh under your breath!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Rule Number Three: The Forty-Eight-Hour Closure Mandate. Abolish the slow-fade forever! If you go out with someone and realize there is no romantic spark, send the Universal Polite Exit Text: 'Hey, I had a great time meeting you, but I did not feel a romantic connection. Wishing you the absolute best!' It takes fifteen seconds, it provides clean closure, and it preserves everyone's dignity."},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Rule Number Four: The Audio Memo Cap. Keep voice notes under ninety seconds until you have shared at least five meals together. Audio memos are for urgent logistics, not unsolicited audio diaries of your morning walk through the park!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Rule Number Five: The Read Receipt Truce. Keep read receipts disabled during the first month of dating. Give each other the grace to live life, respond thoughtfully, and eliminate digital paranoia from early romance."},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] That is The Unwritten Code for this Tuesday morning! If you enjoyed today's episode, hit that Follow button right now on Spotify and Apple Podcasts so you never miss tomorrow morning's drop. Share this episode with a friend who is currently stuck in the dating trenches!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Tomorrow on Wednesday, we are shifting from romance to friendships: the extortion of large birthday dinner tabs, the politics of splitting vacation Airbnbs, and how to escape a runaway group chat without offending everyone. Until tomorrow morning, stay safe out there, and remember: do not break the code!"}
        ]

    # -------------------------------------------------------------------------
    # WEDNESDAY = 2: Friendships & Group Chat Hostages (1,548 words)
    # -------------------------------------------------------------------------
    elif day_idx == 2:
        ep_num = 3
        title = "Birthday Dinner Bill Hostages & Runaway Group Chats"
        summary = "Maya & Julian tackle friendship etiquette: why splitting large group dinner tabs turns into financial extortion, the politics of vacation Airbnb room inequality, and how to escape a runaway group chat without offending everyone."
        turns = [
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Happy Wednesday, everyone! Welcome back to The Unwritten Code. I am Maya Lin alongside Julian Cross, and we are officially at the midpoint of our premiere week! Today, we are taking on a sacred, essential institution of human life: friendships in the digital age. Specifically: the delicate art of lending money to friends, navigating the nightmare of large group dinner tabs, escaping fifty-person runaway group chats, and the unwritten laws of borrowing your best friend's clothes or car."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] [chuckles] Maya, there is no faster way to test the strength of a ten-year friendship than introducing money or a group chat into the mix. You can love someone like a sibling, travel the world together, and stand by them through heartbreak... but the moment a dinner bill lands on the table or someone starts a bachelor party chat thread, human sanity completely falls apart."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] It really does! Let us start with the heavyweight champion of weekend friendship drama: The Twelve-Person Birthday Dinner Tab. You know the exact scenario: a close friend invites twelve people to an upscale tapas restaurant or steakhouse to celebrate their birthday. Person A is on a tight student budget, so they order tap water and a fourteen-dollar bowl of tomato soup. Person B orders three mezcal cocktails, an order of wagyu beef sliders, and two desserts. And then the waiter drops an eight-hundred-dollar check on the table, and Person B cheerfully smiles and says: Hey guys, why don't we just divide it evenly twelve ways to keep things simple?"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [laughs] Oh, the Birthday Tab Communism! It happens every single Saturday night! The person who consumed eighty dollars of prime steak and craft alcohol suddenly discovers a deep philosophical passion for equal wealth redistribution the second the bill arrives! All of a sudden, it is: We are all in this together, comrades! Meanwhile, the poor person in the corner who had iced water and a side salad is being asked to pay seventy-five dollars! That is not keeping things simple; that is legalized extortion under the guise of celebration!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] It is social extortion! And the worst part is nobody wants to speak up because they are terrified of looking cheap or ruining the celebratory birthday mood! But here is what The Unwritten Code says: the burden of fairness rests entirely on the big spender! If you ordered expensive cuts of meat and three cocktails, you do not sit quietly waiting for the table to subsidize your meal. You speak up first, throw down forty extra dollars for your drinks, and then let the remaining balance be split!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Absolutely. Consideration is the foundation of friendship. If you ordered the ribeye and the vintage wine, you do not let your vegetarian friend subsidize your luxury! But now, Maya, let us talk about the digital prison we all live inside: The Never-Ending Group Chat."},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] [groans] The Group Chat Trap! A group chat starts with completely good intentions: Planning Mike's thirty-fifth birthday party next Saturday. Simple, right? But three weeks after the party ends, the group chat refuses to die! It mutates into an endless stream of unhinged political takes, blurry baby photos, inside jokes between two people, and seventy-five notifications an hour!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] And the psychological pressure of trying to leave! If you hit Leave Conversation, the app literally broadcasts a public banner of shame across everyone’s screens: Julian Cross has left the group! It feels like you stood up at Thanksgiving dinner, slammed your chair into the table, and walked out into the snow without saying goodbye!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] It is an act of digital warfare! So what do people do instead? They mute the chat forever! I currently have four group chats muted on my phone with over two thousand unread messages that I will take to my grave before I open!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] [chuckles] We are all running digital ghost towns on our phones! But why should leaving an event chat be considered an insult? When a party is over, you go home! An event group chat should have a natural expiration date."},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] And what about the friend who never replies in the group chat, but watches your Instagram stories five seconds after you post them? We see you, lurkers! We know you have your phone in your hand!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] Oh, the silent spectator! They will not confirm if they are coming to dinner, but they will like a photo of your dog at midnight! Friendship requires active participation, folks. Don't be a ghost in your own community."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] And Julian, what about vacation Airbnb politics? You get eight friends together to rent a cabin for the weekend. Person A books the master suite with a king-sized bed, private balcony, and jacuzzi tub. Person B gets stuck sleeping on a pull-out couch in the drafty living room next to the refrigerator that hums all night. And then Person A calculates the total cost divided by eight equal parts!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [laughs] Oh, the vacation rental hierarchy! That is pure room robbery! If you have the penthouse master bedroom with an ensuite marble bathroom, you pay forty percent of the house cost! The person sleeping on the squeaky futon with dog hair on it should basically stay for free! Square footage and luxury must dictate the split, not simple headcount arithmetic!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] It is common decency! Don't let your friends finance your presidential suite experience while they nurse a sore back on an air mattress that deflates by three in the morning! Respect the comfort levels of the people traveling with you."},
            {"speaker": "Julian", "voice": "Puck", "text": "[playfully] And Maya, what about borrowing personal items from friends? A friend asks to borrow your favorite designer jacket or a specialized power tool for a weekend project. Three months pass, they never mention it, and when you finally ask for it back, they say: Oh yeah, I think it is in the trunk of my car or at my brother's house! Borrowing requires a proactive return timeline!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] The statute of limitations on borrowed items! If you borrow something, the burden of returning it belongs entirely to the borrower! You should not force your friend to conduct a forensic investigation to retrieve their own blender or winter coat! Return it within seven days, clean, and say thank you!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] And what about lending actual money to friends, Maya? A close friend is in a tight spot with rent or car repairs, and they ask for a five-hundred-dollar loan. You want to help because you love them, but the second money changes hands, the dynamic between you changes forever. Every time you see them out grabbing dinner or buying new sneakers, a little voice in the back of your head whispers: Hey, that was my money they just spent!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] [sighs] It creates a toxic surveillance state inside your own mind! You suddenly become their unofficial financial probation officer, auditing their lifestyle choices! Which is why the classic wisdom is so essential: never lend money to a friend unless you are emotionally prepared to never see a single penny of it again. Treat it mentally as a loving gift. If they pay you back, it is a wonderful bonus. If they cannot, you protect your friendship and let it go."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Exactly. If five hundred dollars is going to make you resent them for the next ten years, politely decline upfront and offer other kinds of support! And speaking of emotional drainage, Maya, what about the One-Way Friendship Venting Trap? We all have that one friend who only calls when their life is a three-alarm dumpster fire—their relationship is exploding, their boss is terrible, their landlord is evil. You listen compassionately for fifty straight minutes. And the second they finish, they say: Well, I feel so much better, gotta run! And they never once ask how your week was!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] [groans] You are functioning as an unlicensed, unpaid therapist on speed-dial! Friendship is a reciprocal bridge where two humans share both the light and the dark. It is not an emotional garbage chute where you dump your daily toxicity and drive away! We need balance, mutual curiosity, and active emotional presence."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Exactly. Which brings us to today's ruling. It is time to restore peace, grace, and sanity to our friendships. Maya and Julian, let us codify The New Friendship Code."},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] Here is The Code. Rule Number One: The Friendship Loan Principle. If you ever lend money to a close friend in need, treat it emotionally as a gift. If they repay you, wonderful. If not, protect the human bond above the ledger. If you cannot afford to let it go, politely decline upfront."},
            {"speaker": "Julian", "voice": "Puck", "text": "[playfully] Rule Number Two: The Birthday Dinner Fair-Share Mandate. If you order alcohol, appetizers, or expensive entrees at a large group dinner, you must proactively throw in extra cash before the bill is divided. Never let the person who had tap water pay for your martinis."},
            {"speaker": "Maya", "voice": "Kore", "text": "[chuckles] Rule Number Three: The Group Chat Sunset Law. Any group chat created for a specific event (a trip, a wedding, a birthday) officially expires forty-eight hours after the event concludes. Leaving an expired event chat is no longer an insult—it is polite housekeeping!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[cheerful] Rule Number Four: The Airbnb Room Equity Law. Vacation rental costs must be weighted by room quality and privacy. The king bedroom pays premium; the futon sleeps for peanuts. Never split uneven luxury down the middle."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Rule Number Five: The Seven-Day Borrowing Return Guarantee. If you borrow an item from a friend, return it within seven days in pristine condition without being asked. Return it cleaner than you received it, accompanied by a small treat!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] And Rule Number Six: The One-Way Venting Check. If you have a friend who only calls you when their life is falling apart, but never asks how your week is going... schedule a two-way conversation. Friendship is a bridge, not an emotional trash can!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] That is The Unwritten Code for this Wednesday morning! Make sure to hit that Follow button on Spotify and Apple Podcasts so you never miss tomorrow's episode. Send this one to your friend group chat—if they dare to open it!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Tomorrow on Thursday, we are tackling public spaces: who owns the middle seat armrests on an airplane, and the awkward moment when a tablet screen spins around asking for a twenty-five percent tip on black coffee. Until tomorrow morning, take care of your friends, and remember: do not break the code!"}
        ]

    # -------------------------------------------------------------------------
    # THURSDAY = 3: Public Spaces & Stranger Etiquette (Expanded to 1,600+ words)
    # -------------------------------------------------------------------------
    elif day_idx == 3:
        ep_num = 4
        title = "Airplane Armrest Wars & Tipping Screen Fatigue"
        summary = "Maya & Julian unpack public space dilemmas: the sacred rules of airplane middle seat armrests, reclining your seat into someone's knees, and the modern anxiety of the iPad tip screen spinning around at checkout."
        turns = [
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Good morning, everyone! Welcome back to The Unwritten Code. I am Maya Lin alongside Julian Cross, and today is Thursday, October eighth. We have covered the office, we have survived dating economics, and we have navigated the minefield of friendship group chats. But today, we are stepping out into the wild frontier of human civilization: shared public spaces and our daily encounters with complete strangers."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] [chuckles] Maya, public space is the true test of human evolution. When you are in your own living room, you can put your feet on the coffee table, talk to yourself, and leave dishes wherever you please. But the exact second you step onto a crowded subway car, enter an airport terminal, or walk into a busy neighborhood coffee shop, you sign an invisible social contract with thousands of fellow citizens to behave like a civilized human being. And nowhere is that contract violated more aggressively than at thirty-five thousand feet inside an airplane cabin!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] [laughs] Oh, air travel brings out the absolute worst in humanity! Let us start with the definitive territorial dispute of commercial aviation: The Airplane Armrest Cold War. Three seats in a standard coach row: Window, Middle, and Aisle. Four armrests. Julian, as our resident etiquette scholar, break down the physics, the emotional geography, and the ethics of who actually owns what!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] This is one of the most fundamental, universally agreed-upon unwritten laws, yet half of the flying public behaves like barbarians! Here is the undeniable truth: Window seat gets the wall and the view. Aisle seat gets legroom and easy access to the bathroom. Middle seat gets BOTH ARMRESTS! It is the only consolation prize for being squished between two human bodies for five hours like a pressed sandwich! It is basic human decency!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] Exactly! The middle seat passenger has neither a window to lean against nor easy mobility to stretch their legs in the aisle. If you are sitting in the aisle seat and you try to claim the middle armrest with your sharp elbow, you are committing a human rights violation! The middle seat gets both armrests—case closed, end of debate!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] And what about the Seat Recliner Standoff, Maya? The second the landing gear retracts and the pilot turns off the seatbelt sign, the person in front of you throws their seat all the way back at ninety miles an hour, nearly snapping your laptop screen in half, spilling your ginger ale, and crushing your knees into dust!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[groans] It is the suddenness that kills you! Look, airplanes have reclining seats, so technically you have the mechanical right to recline. But civilized etiquette dictates a polite three-second glance backward! Turn around, see if the person behind you is a six-foot-four basketball player or eating hot noodle soup, and recline slowly by two inches! You do not rocket backwards like an ejection seat!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] And please, for the love of all that is holy, keep your shoes on! An airplane cabin is a shared pressurized tube of recycled oxygen; it is not your private living room rug! Walking barefoot down the airplane aisle to the lavatory is an international crime against hygiene and dignity! Keep your socks and shoes firmly on your feet!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] It truly is! But now, Julian, let us return to solid ground and talk about the modern economic phenomenon sweeping every counter service shop in the world: Tipping Tablet Fatigue."},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [chuckles] The iPad of Guilt! Walk our listeners through this daily ritual, Maya."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] You walk into a bakery. You pick up a bottle of water from the fridge yourself. You walk to the counter. The barista rings it up, does not say a single word, and then spins the glowing iPad screen around with that dreaded sentence: 'It is just going to ask you a quick question!' And you look down, and the pre-selected tip options are twenty percent, twenty-five percent, and thirty percent! For handing you a bottle of water!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] The psychological pressure is suffocating! The employee is staring directly into your eyes, standing six inches away, while your thumb hovers nervously over the screen. If you select No Tip, you feel like the entire line behind you is judging your moral character! But tipping was invented for sit-down service, table delivery, and personal hospitality. When did we start tipping thirty percent for someone turning a screen ninety degrees?!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] Exactly! And it is ruining tipping culture for actual service workers. When people get tipping fatigue on a five-dollar muffin or an iced tea, they stop tipping generously at restaurants where waitstaff and bartenders genuinely depend on gratuity for their living wage. Counter service tipping should never be forced or guilt-induced!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] And what about public audio pollution, Maya? The person walking through a quiet grocery store produce section or sitting in a doctor’s waiting room having an intensely personal speakerphone conversation on maximum volume!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] [groans] Or watching TikTok videos out loud on a morning commuter bus! Headphones were invented in nineteen-ten! They cost five dollars at any gas station! Why must three dozen tired commuters listen to your cousin's dental drama, family custody arguments, or algorithmic dance music while trying to drink their morning coffee?!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] It is pure auditory narcissism. The assumption that the entire world is just background extras in your personal reality TV show. We have to bring accountability and spatial awareness back to public life!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] And Julian, what about escalator and sidewalk passing etiquette? The golden rule of pedestrian transit in every major city on earth is stand on the right, walk on the left! Yet every single morning at major subway stations, two tourists stand side-by-side with oversized rolling luggage completely blocking the escalator path during rush hour!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [laughs] Oh, the escalator roadblock! People behind them are missing trains, sprinting to job interviews, and these two are casually chatting about muffins while forming an impenetrable human barricade! If you are standing still, hug the right rail like your life depends on it! Treat moving walkways like highways with designated passing lanes!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] And what about elevator etiquette, Julian? The doors open on the ground floor of an office tower, and before the ten people inside can even take one step off, someone on the outside charges into the elevator like a battering ram!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] The physics of volume! Two objects cannot occupy the same physical space at the same time! You must let passengers exit before entering! It applies to elevators, subways, and buses. Step aside, form a polite perimeter, let everyone disembark, and then walk in like a civilized member of society!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] And Julian, what about supermarket checkout divider etiquette? You place your twenty groceries onto the conveyor belt, and then you just walk forward without placing the little plastic divider bar behind your groceries! Leaving the person behind you holding a bundle of bananas wondering where your groceries end and theirs begin!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] [warmly] The checkout divider is the baton of civilized retail! Placing the divider bar is not for you; it is a gift of courtesy to the human being standing behind you in line! Take the half-second to slide the bar onto the belt and complete the social contract!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Which brings us to today's ruling. It is time to codify The New Public Space Code."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Here is The Code. Rule Number One: The Middle Armrest Doctrine. In any row of three seats on a plane, train, or theater, the middle seat passenger gets undisputed ownership of both armrests. Respect the middle seat sacrifice."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Rule Number Two: The Counter Service Tip Boundary. Tipping at a counter service register where you ordered standing up and bussed your own table is entirely optional. Feel zero guilt for selecting fifteen percent or skipping the tip on pre-packaged grab-and-go items."},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Rule Number Three: The Recline Warning Rule. Before you recline your seat on an airplane, take a three-second glance backward. Recline gently, not violently, and never recline during meal service."},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] Rule Number Four: The Escalator Right-Lane Mandate. Stand on the right, walk on the left. Never block the passing corridor with bags or bodies during commuting hours."},
            {"speaker": "Julian", "voice": "Puck", "text": "[playfully] Rule Number Five: The Transit Off-Before-On Principle. Always allow passengers exiting an elevator, subway car, or train to completely step off before attempting to step on."},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] Rule Number Six: The Grocery Divider Courtesy. Always place the grocery divider bar behind your items on the conveyor belt. Be the hero the person behind you needs."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] And Rule Number Seven: The Public Audio Prohibition. No speakerphone conversations in elevators, public transit, or waiting rooms. If you are in public without headphones, your phone stays on silent. Protect the collective peace!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] That is The Unwritten Code for this Thursday morning! If you resonated with any of these travel or public space pet peeves, hit that Follow button on Spotify and share this with your favorite frequent flyer!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Tomorrow on Friday, we are closing out our weekday launch with domestic life: roommate sink standoffs, unannounced in-law visits, and the art of kicking out houseguests who will not leave. Until tomorrow morning, walk politely, and remember: do not break the code!"}
        ]

    # -------------------------------------------------------------------------
    # FRIDAY = 4: Domestic Chaos, Roommates & Family Boundaries (Expanded to 1,600+ words)
    # -------------------------------------------------------------------------
    elif day_idx == 4:
        ep_num = 5
        title = "Roommate Sink Standoffs & Uninvited Houseguests"
        summary = "Maya & Julian tackle domestic life: the passive-aggressive 'soaking pan' in the kitchen sink, handling unannounced in-law drop-ins, and the art of making houseguests leave when their welcome expires."
        turns = [
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Happy Friday, everyone! Welcome back to The Unwritten Code. I am Maya Lin alongside Julian Cross, and we have officially made it to the end of our very first week on the air! Today, we are heading inside the four walls of the home to unpack the domestic battlefield: roommates, in-laws, household chores, and houseguests who overstay their welcome."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] [chuckles] Ah, home sweet home. The place where you are supposed to relax, recharge, kick off your shoes, and find sanctuary... until you walk into the kitchen on a Friday morning and find a giant cast-iron skillet filled with murky, brown water sitting in the sink, accompanied by the legendary domestic excuse: 'I'm letting it soak!' Maya, how long is a pan legally allowed to soak before it becomes an act of war?"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] [laughs] Julian, 'I'm letting it soak' is the single greatest lie in domestic history! A pan needs to soak for twenty minutes in warm water. If that skillet has been sitting in soapy water for forty-eight hours, it is no longer soaking—it has developed its own microscopic ecosystem, started growing algae, and gained official citizenship in your apartment!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] Exactly! It is passive-aggressive procrastination. Every roommate knows that 'soaking' is just code for: 'I am waiting for you to get annoyed enough that you will wash it for me!' And then begins the Cold War of dirty dishes, where roommates stack plates higher and higher like a game of culinary Jenga, each refusing to blink first or wash someone else's fork!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] And let us talk about the shared refrigerator economy! When you buy a special carton of oat milk or leftovers from a great restaurant, and you put a little sticky note on it with your name... and two days later, you open the fridge to find two sips left in the carton and your leftovers mysteriously eaten! Julian, what is the penalty for refrigerator theft?"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Immediate loss of kitchen privileges! The rule of a shared fridge is simple: if you did not buy it and your name is not on it, do not touch it! And leaving one swallow of milk in the carton just so you don't have to throw the carton away is a crime against humanity! Leaving an empty container in the fridge is an insult to common sense!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] But now, Julian, let us move from roommates to family boundaries. Specifically: The Unannounced Drop-In. You are on the couch on a Saturday morning in sweatpants, the apartment is messy, you have coffee brewing... and your phone buzzes: 'Hey sweetie, we are downstairs in the driveway with bagels!' Julian, why do parents and in-laws think this is a pleasant surprise?!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [chuckles] It is an ambush! That is not a visit; that is a no-knock raid on your personal life! Even if you love your family dearly, your home requires preparation time! You need thirty minutes to hide clutter, put on real clothes, and mentally prepare for hospitality. Dropping in unannounced with zero warning is an invasion of sovereignty!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Completely! A courtesy text twenty-four hours in advance is not an unreasonable demand—it is basic respect for adult boundaries! But what about the opposite scenario, Julian: The Houseguest Who Refuses to Leave?"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] Oh, Benjamin Franklin said it best: Guests, like fish, begin to smell after three days! Maya, describe the agony of the overstayed guest."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] A friend from out of town asks to stay on your couch for 'the weekend.' Sunday night arrives: they are still on the couch. Monday morning: they are making breakfast in your bathrobe. Tuesday night: they are suggesting TV shows for you to binge-watch together! You are exhausted, your social battery is at negative twenty percent, but you are too polite to say: 'Please get out of my apartment!'"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] [warmly] You start dropping subtle hints that get increasingly desperate! You start slapping both hands onto your knees and sighing loudly: 'Welp! I suppose it's getting late!' You start putting on your pajamas at seven PM. You start vacuuming around their feet while they are watching television! But some guests are completely oblivious to social cues!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] You have to execute the Domestic Irish Exit—which is nearly impossible because it is your own home! You can't leave; you live there! Which is why we need clear, codified rules so nobody has to suffer in silence."},
            {"speaker": "Julian", "voice": "Puck", "text": "[playfully] And what about bathroom thermostat wars, Maya? Roommate A likes the apartment set to seventy-two degrees in winter with the central heater blasting like a sauna. Roommate B wants it at sixty-three degrees with crisp mountain air so they can sleep under four heavy quilts and duvets. And then someone locks the thermostat control box with an acrylic padlock!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] [groans] The thermostat Cold War is literal! Sixty-eight degrees is the universally accepted diplomatic middle ground of indoor climate treaties. If you are freezing at sixty-eight, put on woolen socks, sweatpants, and a fleece sweatshirt. If you are overheating, switch to linen sheets and turn on an oscillating desk fan. Do not turn the living room into a tropical rainforest or an Arctic research station!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] And Maya, what about replacing household consumables like toilet paper and paper towels? When someone finishes the very last square of toilet paper and leaves the naked brown cardboard tube spinning sadly on the metal roller like a tiny monument to domestic laziness!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] That is pure anarchy! The person who uses the final sheet has the sacred legal duty to mount the fresh roll! Not balance it precariously on top of the porcelain toilet tank, not leave it on the bathroom floor, but actually unwrap it and click it onto the spindle!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[playfully] And what about household chore choreographies, Maya? When one roommate spends three hours scrubbing the entire bathroom, wiping tiles, vacuuming rugs, and sanitizing the stove, and the other roommate takes out one half-full bag of trash and proudly announces: Well, we both did our chores today, what a productive morning!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] False equivalency! Cleaning a moldy shower drain is ten times the physical and emotional labor of tying a quick knot on a plastic garbage bag! Household chore distribution must be weighted by actual effort and time, not simple checklist counts! If you take out the trash, you also wipe down all the kitchen counter surfaces!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] And what about loud early morning blender smoothies, Maya? It is six-fifteen on a Saturday morning, everyone else in the house is peacefully sleeping, and Roommate Steve decides that right now is the optimal moment to pulverize four frozen bananas and ice cubes in a high-powered industrial blender that sounds like a jet engine taking off in the hallway!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[groans] [laughs] The morning blender assault! Buy frozen berries that thaw easily, prep your smoothie ingredients the night before in a mason jar, or wrap a thick kitchen towel around the blender base! Respect the morning sleep peace of the people who pay rent under the same roof!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[cheerful] Absolutely! So to close out our launch week, let us officially hand down The New Domestic Code."},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] Here is The Code. Rule Number One: The Soaking Time Limit. A pan may soak for a maximum of four hours. After four hours, that dish must be washed, dried, and put away. Abandoning dishes in the sink for more than twenty-four hours forfeits your right to complain about anything in the apartment."},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Rule Number Two: The Forty-Eight-Hour Houseguest Rule. Unless explicitly agreed upon in advance, couch stays max out at two nights. On night three, the guest must transition to a hotel or head back home. Preserve the friendship; protect the couch."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Rule Number Three: The Two-Hour In-Law Warning. Drop-ins without warning are officially prohibited. Even loving family members must give at least two hours notice before arriving at your doorstep, giving you adequate time to tidy up and wear pants."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Rule Number Four: The Thermostat Treaty. In shared apartments, the thermostat stays between sixty-seven and sixty-nine degrees year-round. Adjust clothing layers before touching the dial."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Rule Number Five: The Spindle Duty. If you use the last sheet of toilet paper or paper towels, you must replace the roll on the spindle immediately. No brown cardboard tombstones left on the roller!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Rule Number Six: The Chore Equity Doctrine. Chore trades must balance actual time and labor. Scrubbing bathrooms equals three kitchen wipe-downs. Balance the burden fairly."},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] And Rule Number Seven: The Refrigerator Replacement Rule. If you take the last sip or bite of a roommate's food, you are obligated to replace it within twenty-four hours. Respect the snacks; preserve the peace!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[cheerful] What a phenomenal week it has been! That is The Unwritten Code for Friday. Don't forget to hit that Follow button right now on Spotify and Apple Podcasts so you are ready for tomorrow morning!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[warmly] Tomorrow on Saturday, we drop our very first Weekend Docket special—unpacking listener-submitted dilemma trials, wedding plus-one disasters, and your wild voicemail confessions. Until tomorrow morning, protect your peace, and remember: do not break the code!"}
        ]

    # -------------------------------------------------------------------------
    # SATURDAY = 5: The Weekend Docket (Deep Dive Special)
    # -------------------------------------------------------------------------
    else:
        ep_num = 6
        title = "The Weekend Docket: Wedding Plus-Ones & Family Holiday Drama"
        summary = "Maya & Julian convene The Weekend Docket to put listener-submitted moral dilemmas on trial: the bridesmaid dress invoice, uninvited wedding plus-ones, and holiday family seating wars."
        turns = [
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] Happy Saturday, everyone! Welcome to the inaugural edition of The Weekend Docket on The Unwritten Code. I am Maya Lin with Julian Cross, and while Alex and Elena on Future Human Daily take their weekends slow with science recaps, we are here with your weekend coffee to put humanity’s messiest real-world dilemmas on trial."},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] That is right, Maya! All week long, we handle quick morning commute debates. But on Saturday morning, the courtroom is officially in session. We take real listener submissions, real drama sent to our inbox, and we hand down the definitive, legally binding verdict of The Unwritten Code."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Our first case on the docket today comes from Amanda in Seattle. Amanda writes: 'Dear Maya and Julian, my cousin is getting married in November. She invited me, but did not give me a plus-one for my boyfriend of four years because they are keeping the guest list small. However, another cousin who has only been dating someone for three months received a plus-one because her partner is friends with the groom. Am I allowed to decline the wedding invitation out of principle, or does that make me a petty monster?' Julian, what is your initial ruling?"},
            {"speaker": "Julian", "voice": "Puck", "text": "[chuckles] Oh, the classic wedding plus-one political minefield! Here is the cold, hard truth: a four-year relationship is not a casual date; that is a committed partnership. Leaving off a partner of four years while granting a plus-one to a three-month fling because the groom likes him for fantasy football is a major etiquette violation! However, declining a wedding out of petty spite ruins family relationships forever. You attend, you smile, you eat the cake, and you leave at nine PM!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] [laughs] Exactly! You don't let wedding politics burn down family bridges for the next thirty years. But you do get to give a slightly smaller wedding gift registry blender! Now our second case comes from Marcus in Atlanta regarding holiday family seating. Marcus writes: 'My in-laws insist on putting adults who are unmarried at the kids table during Thanksgiving, even though I am thirty-two years old and a licensed architect! Can I refuse to sit at the kids table?'"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [laughs] Thirty-two years old eating turkey out of a paper cup with nine-year-olds! That is a felony! The Kids Table has an age cap of sixteen! After age sixteen, you graduate to the adult table regardless of your marital status! Treating a grown professional like an oversized toddler because they don't have a wedding ring on their finger is sheer madness!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] And our third case on the docket comes from Priya in Boston regarding bridesmaid finances. Priya writes: 'I agreed to be a bridesmaid for my college roommate. Last week, the maid of honor sent an itemized invoice for seven hundred and fifty dollars per person for matching custom silk robes, monogrammed luggage tags, and three private bottle service dinners for the bachelorette weekend in Nashville—none of which was discussed in advance! Can I politely push back, or is a bridesmaid legally required to bankroll the bridal fantasy?'"},
            {"speaker": "Julian", "voice": "Puck", "text": "[sighs] [warmly] You have every moral and financial right to push back immediately! A wedding is a celebration of love, not a hostage ransom negotiation where you seize your friends' savings accounts for Instagram photo aesthetics! The maid of honor cannot unilaterally commit other people's bank accounts without unanimous prior consent. Priya, you send a polite, firm note stating your exact budget, and if they throw a tantrum, you step down with your chin held high."},
            {"speaker": "Maya", "voice": "Kore", "text": "[playfully] Completely agree! Now our fourth case on the docket comes from Derek in Denver regarding neighborhood tool borrowing. Derek writes: 'My neighbor borrowed my expensive pressure washer six months ago to clean his driveway. He still has not returned it. Last weekend, I saw him lending my pressure washer to another neighbor across the street! Can I march across the lawn and reclaim my machinery, or do I need to be neighborly and polite?'"},
            {"speaker": "Julian", "voice": "Puck", "text": "[laughs] [groans] He sublet your pressure washer, Derek! That is grand larceny under the guise of suburban neighborliness! You don't lend someone else's borrowed equipment! Derek, you have full legal and moral authorization to walk across the street right now, unplug the pressure washer, coil the hose, and wheel it straight back into your garage while giving a friendly wave!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[laughs] And our final case on today's docket comes from Chloe in Chicago regarding dinner bill ghosting. Chloe writes: 'A group of five coworkers went out for happy hour drinks and appetizers. At seven PM, one coworker stood up, threw a wrinkled ten-dollar bill on the table, said: That should cover my two IPAs and sliders, and bolted out the door. The actual cost of his food and drinks was forty-two dollars with tax and tip! Can we confront him at work on Monday morning?'"},
            {"speaker": "Julian", "voice": "Puck", "text": "[groans] [laughs] Oh, the Dine-and-Dash Colleague! Throwing down a ten-dollar bill on a forty-dollar tab is pure daylight robbery! Yes, you confront him! You send him an itemized payment request at nine-fifteen on Monday morning with zero shame! Do not let coworkers make you pay for their craft beers!"},
            {"speaker": "Maya", "voice": "Kore", "text": "[cheerful] The docket is clear, and the verdicts are final! That is The Weekend Docket for this Saturday. Thank you so much for joining us for our spectacular launch week of The Unwritten Code. Hit that Follow button right now on Spotify and Apple Podcasts so you are ready when Episode Seven drops bright and early on Monday morning!"},
            {"speaker": "Julian", "voice": "Puck", "text": "[warmly] Enjoy your weekend, everyone. Stay safe, stay kind, hold your ground on wedding budgets and pressure washers, and remember: do not break the code!"}
        ]

    # Quality Gate Verification: Enforce minimum 1,500 words for every weekday episode
    word_count = sum(len(t["text"].split()) for t in turns)
    if day_idx < 5 and word_count < 1500:
        raise ValueError(
            f"[QUALITY GATE FAILED] Day {day_idx} ({title}) has {word_count} words! "
            f"Mandatory minimum is 1,500 words to ensure at least 5 minutes of podcast audio."
        )

    return ep_num, title, summary, turns
